version: '3'
services:
  product: 
   build: ./product
   volumes: 
       -  ./product:/usr/src/apps
   ports: 
      - 5001:80


  website: 
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product
